
package es.uma.galvez.isia;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "serviciosweb", targetNamespace = "http://isia.galvez.uma.es/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Serviciosweb {


    /**
     * 
     * @param dni
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLetraDNI", targetNamespace = "http://isia.galvez.uma.es/", className = "es.uma.galvez.isia.GetLetraDNI")
    @ResponseWrapper(localName = "getLetraDNIResponse", targetNamespace = "http://isia.galvez.uma.es/", className = "es.uma.galvez.isia.GetLetraDNIResponse")
    @Action(input = "http://isia.galvez.uma.es/serviciosweb/getLetraDNIRequest", output = "http://isia.galvez.uma.es/serviciosweb/getLetraDNIResponse")
    public int getLetraDNI(
        @WebParam(name = "dni", targetNamespace = "")
        int dni);

    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hola", targetNamespace = "http://isia.galvez.uma.es/", className = "es.uma.galvez.isia.Hola")
    @ResponseWrapper(localName = "holaResponse", targetNamespace = "http://isia.galvez.uma.es/", className = "es.uma.galvez.isia.HolaResponse")
    @Action(input = "http://isia.galvez.uma.es/serviciosweb/holaRequest", output = "http://isia.galvez.uma.es/serviciosweb/holaResponse")
    public String hola(
        @WebParam(name = "name", targetNamespace = "")
        String name);

    /**
     * 
     * @param url
     * @return
     *     returns byte[]
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nubeEtiquetas", targetNamespace = "http://isia.galvez.uma.es/", className = "es.uma.galvez.isia.NubeEtiquetas")
    @ResponseWrapper(localName = "nubeEtiquetasResponse", targetNamespace = "http://isia.galvez.uma.es/", className = "es.uma.galvez.isia.NubeEtiquetasResponse")
    @Action(input = "http://isia.galvez.uma.es/serviciosweb/nubeEtiquetasRequest", output = "http://isia.galvez.uma.es/serviciosweb/nubeEtiquetasResponse")
    public byte[] nubeEtiquetas(
        @WebParam(name = "URL", targetNamespace = "")
        String url);

}
